# Site settings
title: Code Farmer's Home 
email: codefarmer@codefarmer.me
description: > # this means to ignore newlines until "baseurl:"
  Code farmer's personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codefarmer.me" # the base hostname & protocol for your site
twitter_username: patrickzzy
github_username:  patrickzzy

# Build settings
markdown: kramdown
